# Intel Compilers
#set(CMAKE_Fortran_COMPILER "mpif90" CACHE STRING "" FORCE)
#set(CMAKE_Fortran_FLAGS "-O3 -ip -fp-model precise" CACHE STRING "" FORCE)
#set(Fortran_MIN_FLAGS "-O0 -fp-model precise" CACHE STRING "" FORCE)
#set(CMAKE_C_COMPILER "icc" CACHE STRING "" FORCE)
#set(CMAKE_C_FLAGS "-O3 -ip -fp-model precise -std=gnu99" CACHE STRING "" FORCE)
#set(CMAKE_CXX_COMPILER "icpc" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "-O3 -ip -fp-model precise" CACHE STRING "" FORCE)
#set(LIB_PATHS "/opt/intel/mkl/lib/intel64" CACHE STRING "" FORCE)
#set(LIBS "mkl_intel_lp64 mkl_sequential mkl_core mkl_blacs_intelmpi_lp64 mkl_scalapack_lp64" CACHE STRING "" FORCE)
#set(USE_MPI ON CACHE BOOL "" FORCE)
#set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
#set(USE_LIBXC ON CACHE BOOL "" FORCE)
#set(USE_HDF5 OFF CACHE BOOL "" FORCE)
#set(USE_RLSY ON CACHE BOOL "" FORCE)
#set(ELPA2_KERNEL "" CACHE STRING "Change to AVX/AVX2/AVX512 if running on Intel processors" FORCE)

# GNU Compilers
set(CMAKE_Fortran_COMPILER mpif90 CACHE STRING "")
set(CMAKE_Fortran_FLAGS "-Ofast -Wall -mtune=a64fx -mcpu=a64fx -march=armv8.2-a+sve -fopt-info-vec -fopenmp -fallow-argument-mismatch -ffree-line-length-none" CACHE STRING "")
#set(CMAKE_Fortran_FLAGS "-O2 -fallow-argument-mismatch -ffree-line-length-none" CACHE STRING "")
set(Fortran_MIN_FLAGS "-O0 -ffree-line-length-none" CACHE STRING "")
set(CMAKE_C_COMPILER mpicc CACHE STRING "")
set(CMAKE_C_FLAGS "-Ofast -Wall -mtune=a64fx -mcpu=a64fx -march=armv8.2-a+sve -fopt-info-vec -fopenmp" CACHE STRING "")
#set(CMAKE_C_FLAGS "-O2" CACHE STRING "")
set(CMAKE_CXX_COMPILER mpicxx CACHE STRING "")
set(CMAKE_CXX_FLAGS "-Ofast -Wall -mtune=a64fx -mcpu=a64fx -march=armv8.2-a+sve -fopt-info-vec -fopenmp" CACHE STRING "")
#set(CMAKE_CXX_FLAGS "-O2" CACHE STRING "")
#set(USE_EXTERNAL_ELPA ON CACHE BOOL "" FORCE)
set(LIB_PATHS "/lustre/software/scalapack/gcc13/mvapich2/armpl23.10/2.2.0/lib/" "/lustre/software/openblas/gcc13/0.3.21/lib/" CACHE STRING "" FORCE)
set(LIBS "scalapack openblas" CACHE STRING "" FORCE)
#set(LIB_PATHS "/lustre/scratch/danaoconnor/software/elpa/lib/" "/lustre/software/scalapack/gcc13/armpl22.1/2.2.0/lib/" "/lustre/software/openblas/gcc13/0.3.21/lib/" CACHE STRING "" FORCE)
#set(LIBS "elpa scalapack openblas" CACHE STRING "" FORCE)
#set(INC_PATHS "/lustre/scratch/danaoconnor/software/elpa/include/elpa-2024.03.001.rc1/modules/" CACHE STRING "" FORCE)
set(USE_MPI ON CACHE BOOL "" FORCE)
set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
set(USE_LIBXC ON CACHE BOOL "" FORCE)
set(USE_HDF5 OFF CACHE BOOL "" FORCE)
set(USE_RLSY ON CACHE BOOL "" FORCE)
#set(LD_FLAGS '-lscalapack')
#set(LIB_PATHS "/lustre/scratch/danaoconnor/software/elpa/" CACHE STRING "" FORCE)

# Cray Compilers
#set(CMAKE_Fortran_COMPILER ftn CACHE STRING "")
#set(Fortran_MIN_FLAGS "-O0" CACHE STRING "")
#set(CMAKE_Fortran_FLAGS "-O3 -hfp3" CACHE STRING "")
#set(CMAKE_C_COMPILER cc CACHE STRING "")
#set(CMAKE_C_FLAGS "-O2 -funroll-loops -ffast-math" CACHE STRING "")
#set(CMAKE_CXX_COMPILER c++ CACHE STRING "")
#set(CMAKE_CXX_FLAGS "-O2 -funroll-loops -ffast-math" CACHE STRING "")
#set(USE_MPI ON CACHE BOOL "" FORCE)
#set(USE_SCALAPACK ON CACHE BOOL "" FORCE)
#set(USE_LIBXC ON CACHE BOOL "" FORCE)
